""" Used for printing the greek alphabet in a nice form """
REPLACE_DIC = {"alpha" : u"\u03b1",
               "beta" : u"\u03b2",
               "gamma" : u"\u03b3",
               "delta" : u"\u03b4",
               "epsilon" : u"\u03b5",
               "zeta" : u"\u03b6",
               "eta" : u"\u03b7",
               "theta" : u"\u03b8",
               "iota" : u"\u03b9",
               "kappa" : u"\u03ba",
               "my" : u"\u03bc",
               "ny" : u"\u03bd",
               "xi" : u"\u03be",
               "omikron" : u"\u03bf",
               "rho" : u"\u03c1",
               "sigma" : u"\u03c3",
               "tau" : u"\u03c4",
               "ypsilon" : u"\u03c5",
               "phi" : u"\u03c6",
               "chi" : u"\u03c7",
               "psi" : u"\u03c8",
               "omega" : u"\u03c9"}
